crm/urls.py
from django.contrib import admin
from django.urls import path, include

from users import views

urlpatterns = [
    # admin后台页面
    path('admin/', admin.site.urls),
    # index重定向
    path('', views.index, name='index'),
    # home首页
    path('home/', views.home, name='home'),
    # week周数据汇总
    path('week/', views.week, name='week'),
    # path('week/group', views.week_group, name='week_group'),
    path('week/all', views.week_all, name='week_all'),
    # 用户模块
    path('user/', include('users.urls')),
    # 客户信息模块
    path('customer/', include('customer.urls')),
    # 联系人信息模块
    path('liaison/', include('liaison.urls')),
    # 拜访记录模块
    path('record/', include('record.urls')),
    # 商机模块
    path('business/', include('business.urls')),
    # okr模块
    path('okr/', include('okr.urls'))
]

okr/urls.py
from django.urls import path

from okr import views

urlpatterns = [
    path('', views.okr, name='okr'),
    # 添加个人okr目标
    path('add/', views.okr_add, name='okr_add'),
    # 修改个人okr目标
    path('edit/<int:pk>', views.okr_edit, name='okr_edit'),
    # 完成个人okr目标，即讲该字段删除
    path('finish/<int:pk>', views.okr_finish, name='okr_finish'),
]

okr/models.py
from django.db import models

# Create your models here.
from users.models import User
from utils import constants


class Okr(models.Model):
    """okr个人目标"""
    object = models.CharField(verbose_name='目标', max_length=255)
    key1 = models.CharField(verbose_name='关键成果1', max_length=255, null=True, blank=True)
    key1_true = models.SmallIntegerField(verbose_name='完成情况1', choices=constants.OKR_FINISH, null=True, blank=True)
    key2 = models.CharField(verbose_name='关键成果2', max_length=255, null=True, blank=True)
    key2_true = models.SmallIntegerField(verbose_name='完成情况2', choices=constants.OKR_FINISH, null=True, blank=True)
    key3 = models.CharField(verbose_name='关键成果3', max_length=255, null=True, blank=True)
    key3_true = models.SmallIntegerField(verbose_name='完成情况3', choices=constants.OKR_FINISH, null=True, blank=True)
    results = models.CharField(verbose_name='衡量标准', max_length=255, null=True, blank=True)
    finish = models.CharField(verbose_name='实际达成', max_length=255, null=True, blank=True)

    user = models.ForeignKey(User, verbose_name='创建人', on_delete=models.CASCADE)
    created_at = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='修改时间', auto_now=True)
    is_valid = models.BooleanField(verbose_name='是否有效', default=True)

    class Meta:
        db_table = 'okr'
        verbose_name = verbose_name_plural = 'okr'
        ordering = ['-created_at']

    def __str__(self):
        return self.object

okr/forms.py
from django.forms import ModelForm

from okr.models import Okr


class OkrForm(ModelForm):
    """okr表单"""
    class Meta:
        model = Okr
        exclude = ['is_valid', 'created_at', 'updated_at']

okr/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from okr.forms import OkrForm
from okr.models import Okr


def okr(request):
    """okr展示"""
    user = request.session.get('user_id')
    okrs = Okr.objects.filter(user=user).exclude(is_valid=False)
    return render(request, 'okr.html', {
        'okrs': okrs
    })


def okr_add(request):
    """添加个人okr目标"""
    user_id = request.session.get('user_id')
    okr = Okr.objects.filter(user=user_id)
    if request.method == 'POST':
        form = OkrForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('okr')
        else:
            print(form.errors.as_json)
    else:
        form = OkrForm()
    return render(request, 'okr_add.html', {
        'okr': okr,
        'form': form
    })


def okr_edit(request, pk):
    """修改okr"""
    user = request.session.get('user_id')
    okr = get_object_or_404(Okr, pk=pk, user=user, is_valid=True)
    if request.method == 'POST':
        form = OkrForm(data=request.POST, instance=okr)
        if form.is_valid():
            form.save()
            return redirect('okr')
        else:
            print(form.errors.as_json)
    else:
        form = OkrForm(instance=okr)
    return render(request, 'okr_edit.html', {
        'form': form,
        'pk': pk
    })


def okr_finish(request, pk):
    """okr完成，即删除"""
    user = request.session.get('user_id')
    okr = get_object_or_404(Okr, pk=pk, user=user, is_valid=True)
    okr.delete()
    return redirect('okr')

okr/templates/okr.html
{% extends 'base.html' %}

{% block title %}
  <title>OKR</title>
{% endblock %}

{% block container %}
  <blockquote class="layui-elem-quote">
    <a href="javascript:;">首页</a>
    &ensp;/&ensp;
    <a href="javascript:;">OKR</a>
  </blockquote>

  <hr class="layui-bg-green">

  <div class="layui-card">
    <div class="layui-card-body">

      <table class="layui-table">
        <colgroup>
          <col width="16%">
          <col width="20%">
          <col width="16%">
          <col width="16%">
          <col width="16%">
          <col width="16%">
        </colgroup>
        <thead>
        <tr>
          <th>目标</th>
          <th>关键成果</th>
          <th>完成情况</th>
          <th>衡量指标</th>
          <th>实际达成</th>
          <th>操作</th>
        </tr>
        </thead>
        <tbody>
        <!--数据-->
        {% for okr in okrs %}
          <tr>
            <td rowspan="3">
              <a href="{% url 'okr_edit' okr.pk %}" style="color: #1E9FFF">
                {{ okr.object }}
              </a>
            </td>
            <td>
              {{ okr.key1|default_if_none:'' }}
            </td>
            <td>
              {{ okr.get_key1_true_display|default_if_none:'' }}
            </td>
            <td rowspan="3">
              {{ okr.results|default_if_none:'' }}
            </td>
            <td rowspan="3">
              {{ okr.finish|default_if_none:'' }}
            </td>
            <td rowspan="3">
              <a class="layui-btn layui-btn-sm layui-btn-normal"
                 onclick="return finishOkr();" href="{% url 'okr_finish' okr.pk %}">完成该目标</a>
            </td>
          </tr>
          <tr>
            <td>
              {{ okr.key2|default_if_none:'' }}
            </td>
            <td>
              {{ okr.get_key2_true_display|default_if_none:'' }}
            </td>
          </tr>
          <tr>
            <td>
              {{ okr.key3|default_if_none:'' }}
            </td>
            <td>
              {{ okr.get_key3_true_display|default_if_none:'' }}
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>

    </div>
  </div>
{% endblock %}

{% block footer %}
  <script>
      layui.use(['element', 'layer'], function () {
          var element = layui.element;
          var layer = layui.layer;

          //监听折叠
          /*element.on('collapse(test)', function (data) {
              layer.msg('展开状态：' + data.show);
          });*/
      });
  </script>
  <script type="text/javascript" language="JavaScript">
      function finishOkr() {
          if (confirm("确认后移除该目标记录？")) {
              return true;
          } else {
              return false;
          }
      }
  </script>
{% endblock %}

okr/templates/okr_add.html
{% extends 'base.html' %}

{% block title %}
  <title>添加OKR个人目标</title>
{% endblock %}

{% block container %}
  <blockquote class="layui-elem-quote">
    <a href="{% url 'okr' %}">OKR</a>
    &ensp;/&ensp;
    <a href="javascript:;">添加OKR</a>
  </blockquote>

  <hr class="layui-bg-green">

  <!--客户商机详情-->
  <div class="layui-row">
    <!--客户基本信息-->
    <form class="layui-form" action="." method="post">
      {% csrf_token %}
      <div class="layui-row">
        <blockquote class="layui-elem-quote layui-quote-nm">OKR详情</blockquote>
        <div class="layui-form-item layui-col-md6">
          <label class="layui-form-label"><span style="color: red">* </span>目标</label>
          <div class="layui-input-block">
            <input type="text" name="object" required lay-verify="required"
                   autocomplete="off" class="layui-input" value="">
            {{ form.object.errors }}
          </div>
        </div>

        <div class="layui-row">
          <div class="layui-col-md6">
            <div class="layui-form-item">
              <label class="layui-form-label">关键成果(1)</label>
              <div class="layui-input-block">
                <input type="text" name="key1" autocomplete="off" class="layui-input" value="">
                {{ form.key1.errors }}
              </div>
            </div>
          </div>
          <div class="layui-col-md3">
            <div class="layui-form-item">
              <label class="layui-form-label">完成情况(1)</label>
              <div class="layui-input-block">
                {{ form.key1_true }}
                {{ form.key1_true.errors }}
              </div>
            </div>
          </div>
        </div>

        <div class="layui-row">
          <div class="layui-col-md6">
            <div class="layui-form-item">
              <label class="layui-form-label">关键成果(2)</label>
              <div class="layui-input-block">
                <input type="text" name="key2" autocomplete="off" class="layui-input" value="">
                {{ form.key2.errors }}
              </div>
            </div>
          </div>
          <div class="layui-col-md3">
            <div class="layui-form-item">
              <label class="layui-form-label">完成情况(2)</label>
              <div class="layui-input-block">
                {{ form.key2_true }}
                {{ form.key2_true.errors }}
              </div>
            </div>
          </div>
        </div>

        <div class="layui-row">
          <div class="layui-col-md6">
            <div class="layui-form-item">
              <label class="layui-form-label">关键成果(3)</label>
              <div class="layui-input-block">
                <input type="text" name="key3" autocomplete="off" class="layui-input" value="">
                {{ form.key3.errors }}
              </div>
            </div>
          </div>

          <div class="layui-col-md3">
            <div class="layui-form-item">
              <label class="layui-form-label">完成情况(3)</label>
              <div class="layui-input-block">
                {{ form.key3_true }}
                {{ form.key3_true.errors }}
              </div>
            </div>
          </div>
        </div>

        <div class="layui-form-item layui-col-md6">
          <label class="layui-form-label">衡量标准</label>
          <div class="layui-input-block">
            <input type="text" name="results" autocomplete="off" class="layui-input" value="">
            {{ form.results.errors }}
          </div>
        </div>
        <div class="layui-form-item layui-col-md6">
          <label class="layui-form-label">实际达成</label>
          <div class="layui-input-block">
            <input type="text" name="finish" autocomplete="off" class="layui-input" value="">
            {{ form.finish.errors }}
          </div>
        </div>
      </div>
      {# 隐藏的表单，用户字段 #}
      <input type="hidden" name="user"
             autocomplete="off" class="layui-input"
             value="{{ request.session.user_id }}">
      {# 隐藏的表单，用户字段 #}
      <div class="layui-form-item">
        <div class="layui-input-block">
          <button class="layui-btn" lay-submit lay-filter="formDemo">添加</button>
        </div>
      </div>
    </form>
    <!--客户基本信息结束-->
  </div>
  <hr>
  <!--客户商机详情结束-->
{% endblock %}

{% block footer %}
  <script>
      //JavaScript代码区域
      layui.use(['element', 'form', 'jquery'], function () {
          var element = layui.element
              , form = layui.form
              , $ = layui.jquery;
      });
  </script>
{% endblock %}

okr/templates/okr_edit.html
{% extends 'base.html' %}

{% block title %}
  <title>修改OKR个人目标--{{ form.object.value }}</title>
{% endblock %}

{% block container %}
  <blockquote class="layui-elem-quote">
    <a href="{% url 'okr' %}">OKR</a>
    &ensp;/&ensp;
    <a href="javascript:;">修改OKR</a>
    &ensp;/&ensp;
    <a href="javascript:;">{{ form.object.value }}</a>
  </blockquote>

  <hr class="layui-bg-green">

  <!--客户商机详情-->
  <div class="layui-row">
    <!--客户基本信息-->
    <form class="layui-form" action="{% url 'okr_edit' pk %}" method="post">
      {% csrf_token %}
      <div class="layui-row">
        <blockquote class="layui-elem-quote layui-quote-nm">OKR详情</blockquote>
        <div class="layui-form-item layui-col-md6">
          <label class="layui-form-label"><span style="color: red">* </span>目标</label>
          <div class="layui-input-block">
            <input type="text" name="object" required lay-verify="required"
                   autocomplete="off" class="layui-input" value="{{ form.object.value|default_if_none:'' }}">
            {{ form.object.errors }}
          </div>
        </div>

        <div class="layui-row">
          <div class="layui-col-md6">
            <div class="layui-form-item">
              <label class="layui-form-label">关键成果(1)</label>
              <div class="layui-input-block">
                <input type="text" name="key1" autocomplete="off" class="layui-input" value="{{ form.key1.value|default_if_none:'' }}">
                {{ form.key1.errors }}
              </div>
            </div>
          </div>
          <div class="layui-col-md3">
            <div class="layui-form-item">
              <label class="layui-form-label">完成情况(1)</label>
              <div class="layui-input-block">
                {{ form.key1_true }}
                {{ form.key1_true.errors }}
              </div>
            </div>
          </div>
        </div>

        <div class="layui-row">
          <div class="layui-col-md6">
            <div class="layui-form-item">
              <label class="layui-form-label">关键成果(2)</label>
              <div class="layui-input-block">
                <input type="text" name="key2" autocomplete="off" class="layui-input" value="{{ form.key2.value|default_if_none:'' }}">
                {{ form.key2.errors }}
              </div>
            </div>
          </div>
          <div class="layui-col-md3">
            <div class="layui-form-item">
              <label class="layui-form-label">完成情况(2)</label>
              <div class="layui-input-block">
                {{ form.key2_true }}
                {{ form.key2_true.errors }}
              </div>
            </div>
          </div>
        </div>

        <div class="layui-row">
          <div class="layui-col-md6">
            <div class="layui-form-item">
              <label class="layui-form-label">关键成果(3)</label>
              <div class="layui-input-block">
                <input type="text" name="key3" autocomplete="off" class="layui-input" value="{{ form.key3.value|default_if_none:'' }}">
                {{ form.key3.errors }}
              </div>
            </div>
          </div>

          <div class="layui-col-md3">
            <div class="layui-form-item">
              <label class="layui-form-label">完成情况(3)</label>
              <div class="layui-input-block">
                {{ form.key3_true }}
                {{ form.key3_true.errors }}
              </div>
            </div>
          </div>
        </div>

        <div class="layui-form-item layui-col-md6">
          <label class="layui-form-label">衡量标准</label>
          <div class="layui-input-block">
            <input type="text" name="results" autocomplete="off" class="layui-input" value="{{ form.results.value|default_if_none:'' }}">
            {{ form.results.errors }}
          </div>
        </div>
        <div class="layui-form-item layui-col-md6">
          <label class="layui-form-label">实际达成</label>
          <div class="layui-input-block">
            <input type="text" name="finish" autocomplete="off" class="layui-input" value="{{ form.finish.value|default_if_none:'' }}">
            {{ form.finish.errors }}
          </div>
        </div>
      </div>
      {# 隐藏的表单，用户字段 #}
      <input type="hidden" name="user"
             autocomplete="off" class="layui-input"
             value="{{ request.session.user_id }}">
      {# 隐藏的表单，用户字段 #}
      <div class="layui-form-item">
        <div class="layui-input-block">
          <button class="layui-btn" lay-submit lay-filter="formDemo">修改</button>
        </div>
      </div>
    </form>
    <!--客户基本信息结束-->
  </div>
  <hr>
  <!--客户商机详情结束-->
{% endblock %}

{% block footer %}
  <script>
      //JavaScript代码区域
      layui.use(['element', 'form', 'jquery'], function () {
          var element = layui.element
              , form = layui.form
              , $ = layui.jquery;
      });
  </script>
{% endblock %}