crm/urls.py
from django.contrib import admin
from django.urls import path, include

from users import views

urlpatterns = [
    # admin后台页面
    path('admin/', admin.site.urls),
    # index重定向
    path('', views.index, name='index'),
    # home首页
    path('home/', views.home, name='home'),
    # week周数据汇总
    path('week/', views.week, name='week'),
    # path('week/group', views.week_group, name='week_group'),
    path('week/all', views.week_all, name='week_all'),
    # 用户模块
    path('user/', include('users.urls')),
    # 客户信息模块
    path('customer/', include('customer.urls')),
    # 联系人信息模块
    path('liaison/', include('liaison.urls')),
    # 拜访记录模块
    path('record/', include('record.urls')),
    # 商机模块
    path('business/', include('business.urls')),
    # okr模块
    path('okr/', include('okr.urls'))
]

customer/urls.py
from django.urls import path, include

from customer import views
from customer.views import CustomerView

urlpatterns = [
    # 查看客户
    path('', CustomerView.as_view(), name='customer'),
    # 添加客户
    path('add/', views.customer_add, name='customer_add'),
    # 查看和修改客户
    path('detail/<int:pk>', views.customer_detail, name='customer_detail'),
    # 单个页面进行修改
    path('edit/<int:pk>', views.customer_edit, name='customer_edit'),
    # 删除客户
    path('delete/<int:pk>', views.customer_delete, name='customer_delete'),

    # 客户信息的地址维护
    # 客户收货地址
    path('address/shop/<int:pk>', views.address_shop, name='address_shop'),
    # 客户发票地址
    path('address/invoice/<int:pk>', views.address_invoice, name='address_invoice'),

    # 团队所有客户
    path('group/', views.customer_group, name='customer_group'),

    # 所有客户列表
    path('all/', views.customer_all, name='customer_all'),
    # 客户详情
    path('all/detail/<int:pk>', views.customer_all_detail, name='customer_all_detail'),

    # 导出所有客户信息
    path('export/customer', views.export_customer, name='export_customer'),

    # 下面全都是在客户详情里面的操作
    # 客户详情页添加联系人
    path('detail/<int:pk>/add/liaison', views.customer_add_liaison, name='customer_add_liaison'),
    # 客户详情页添加拜访记录
    path('detail/<int:pk>/add/record', views.customer_add_record, name='customer_add_record'),
    # 客户详情页添加商机
    path('detail/<int:pk>/add/business', views.customer_add_business, name='customer_add_business'),

    # 客户详情页修改联系人
    path('detail/<int:pk>/edit/liaison', views.customer_edit_liaison, name='customer_edit_liaison'),
    # 客户详情页修改拜访记录
    path('detail/<int:pk>/edit/record', views.customer_edit_record, name='customer_edit_record'),
    # 客户详情页修改商机
    path('detail/<int:pk>/edit/business', views.customer_edit_business, name='customer_edit_business'),

    # 客户详情页删除联系人
    path('detail/<int:pk>/delete/liaison', views.customer_delete_liaison, name='customer_delete_liaison'),
    # 客户详情页删除拜访记录
    path('detail/<int:pk>/delete/record', views.customer_delete_record, name='customer_delete_record'),
    # 客户详情页删除商机
    path('detail/<int:pk>/delete/business', views.customer_delete_business, name='customer_delete_business'),

    # 客户详情页查看联系人
    path('detail/<int:pk>/detail/liaison', views.customer_detail_liaison, name='customer_detail_liaison'),
    # 客户详情页查看拜访记录
    path('detail/<int:pk>/detail/record', views.customer_detail_record, name='customer_detail_record'),
    # 客户详情页查看商机
    path('detail/<int:pk>/detail/business', views.customer_detail_business, name='customer_detail_business'),
]

business/models.py
from django.db import models

# Create your models here.
from customer.models import Customer
from users.models import User
from utils import constants


class Business(models.Model):
    """客户商机"""
    name = models.CharField(verbose_name='商机名称', max_length=64)
    customer = models.ForeignKey(Customer, verbose_name='商机客户', on_delete=models.CASCADE)
    winning_rate = models.SmallIntegerField(verbose_name='赢单率', choices=constants.BUSINESS_WINNING, default=constants.WINNING_ERSHI)
    money = models.CharField(verbose_name='预估金额', max_length=16, blank=True, null=True)
    remarks = models.CharField(verbose_name='商机备注', max_length=255, blank=True, null=True)
    user = models.ForeignKey(User, verbose_name='创建人', related_name='customer_business', on_delete=models.CASCADE)

    created_at = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='修改时间', auto_now=True)
    is_valid = models.BooleanField(verbose_name='是否有效', default=True)

    class Meta:
        db_table = 'business'
        verbose_name = verbose_name_plural = "客户商机"
        ordering = ['-created_at']

    def __str__(self):
        return self.name

customer/models.py

from django.db import models

# Create your models here.
from users.models import User
from utils import constants


class Customer(models.Model):
    """客户模型"""
    name = models.CharField(verbose_name='客户名称', max_length=64, unique=True)
    rank = models.SmallIntegerField(verbose_name='客户级别', choices=constants.CUSTOMER_RANK, default=constants.RANK_NORMAL)
    website = models.CharField(verbose_name='客户网址', max_length=255, blank=True, null=True)
    scale = models.SmallIntegerField(verbose_name='客户规模', choices=constants.CUSTOMER_SCALE, default=constants.SCALE_TEN, null=True, blank=True)
    nature = models.SmallIntegerField(verbose_name='客户性质', choices=constants.CUSTOMER_NATURE, default=constants.NATURE_YX, null=True, blank=True)
    industry = models.SmallIntegerField(verbose_name='客户行业', choices=constants.CUSTOMER_INDUSTRY, default=constants.INDUSTRY_JTSB, null=True, blank=True)
    remarks = models.CharField(verbose_name='客户备注', max_length=255, blank=True, null=True)
    user = models.ForeignKey(User, verbose_name='创建人', related_name='customer', on_delete=models.CASCADE)
    is_valid = models.BooleanField(verbose_name='是否有效', default=True)
    created_at = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='修改时间', auto_now=True)

    class Meta:
        db_table = 'customer'
        verbose_name = verbose_name_plural = "客户"
        ordering = ['-created_at']

    def __str__(self):
        return self.name


class CustomerShop(models.Model):
    """客户收货地址信息"""
    customer = models.OneToOneField(Customer, verbose_name='客户名称', related_name='customer_shop', on_delete=models.CASCADE)
    shop_province = models.CharField(verbose_name='收货省份', max_length=32, blank=True, null=True)
    shop_city = models.CharField(verbose_name='收货市区', max_length=32, blank=True, null=True)
    shop_area = models.CharField(verbose_name='收货区域', max_length=32, blank=True, null=True)
    shop_town = models.CharField(verbose_name='收货街道', max_length=32, blank=True, null=True)
    shop_address = models.CharField(verbose_name='收货详细地址', max_length=64, blank=True, null=True)
    shop_username = models.CharField(verbose_name='收货地收货人', max_length=32, blank=True, null=True)
    shop_phone = models.CharField(verbose_name='收货收货人电话', max_length=32, blank=True, null=True)

    created_at = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='修改时间', auto_now=True)

    def shop_address_add(self, pk):
        self.customer_id = pk
        self.save()
        self.refresh_from_db()

    class Meta:
        db_table = 'customer_shop'
        verbose_name = verbose_name_plural = "客户收货地址信息"
        ordering = ['-created_at']

    def __str__(self):
        return self.customer.name


class CustomerInvoice(models.Model):
    """客户发票地址信息"""
    customer = models.OneToOneField(Customer, verbose_name='客户名称', related_name='customer_invoice', on_delete=models.CASCADE)
    invoice_province = models.CharField(verbose_name='发票省份', max_length=32, blank=True, null=True)
    invoice_city = models.CharField(verbose_name='发票市区', max_length=32, blank=True, null=True)
    invoice_area = models.CharField(verbose_name='发票区域', max_length=32, blank=True, null=True)
    invoice_town = models.CharField(verbose_name='发票街道', max_length=32, blank=True, null=True)
    invoice_address = models.CharField(verbose_name='发票详细地址', max_length=64, blank=True, null=True)
    invoice_username = models.CharField(verbose_name='发票地收货人', max_length=32, blank=True, null=True)
    invoice_phone = models.CharField(verbose_name='发票收货人电话', max_length=32, blank=True, null=True)

    created_at = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='修改时间', auto_now=True)

    class Meta:
        db_table = 'customer_invoice'
        verbose_name = verbose_name_plural = "客户发票地址信息"
        ordering = ['-created_at']

    def __str__(self):
        return self.customer.name

liaison/models.py
from django.db import models

from customer.models import Customer
from users.models import User
from utils import constants


class Liaison(models.Model):
    """联系人模型"""
    customer = models.ForeignKey(Customer, verbose_name='客户', related_name='liaison', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='联系人姓名', max_length=64)
    phone = models.CharField(verbose_name='联系人电话', max_length=11)
    job = models.SmallIntegerField(verbose_name='职称', choices=constants.LIAISON_JOB, default=constants.JOB_BUSINESS)
    injob = models.SmallIntegerField(verbose_name='是否在职', choices=constants.LIAISON_INJOB, default=constants.INJOB_YES)
    wx = models.CharField(verbose_name='微信', max_length=64, blank=True, null=True)
    qq = models.CharField(verbose_name='QQ', max_length=64, blank=True, null=True)
    email = models.EmailField(verbose_name='电子邮箱', max_length=64, blank=True, null=True)
    hobby = models.CharField(verbose_name='兴趣爱好', max_length=128, blank=True, null=True)
    birthday = models.CharField(verbose_name='生日', max_length=64, blank=True, null=True)
    remarks = models.CharField(verbose_name='联系人备注', max_length=255, blank=True, null=True)
    user = models.ForeignKey(User, verbose_name='创建人', related_name='liaison', on_delete=models.CASCADE)

    is_valid = models.BooleanField(verbose_name='是否有效', default=True)
    created_at = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='修改时间', auto_now=True)

    class Meta:
        db_table = 'liaison'
        verbose_name = verbose_name_plural = "联系人"
        ordering = ['-created_at']

    def __str__(self):
        return self.name

record/models.py
from django.db import models

# Create your models here.
from users.models import User
from customer.models import Customer
from utils import constants


class Record(models.Model):
    """客户拜访记录模型"""
    theme = models.CharField(verbose_name='拜访主题', max_length=256)
    customer = models.ForeignKey(Customer, verbose_name='客户', related_name='customer_record', on_delete=models.CASCADE)
    status = models.SmallIntegerField(verbose_name='客户拜访方式', choices=constants.RECORD_STATUS, default=constants.STATUS_XS)
    user = models.ForeignKey(User, verbose_name='创建人', related_name='customer_record', on_delete=models.CASCADE)
    main = models.TextField(verbose_name='主要事宜', max_length=1000, null=True, blank=True)
    next = models.TextField(verbose_name='后期规划', max_length=1000, null=True, blank=True)
    remarks = models.CharField(verbose_name='拜访备注', max_length=255, blank=True, null=True)

    created_at = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='修改时间', auto_now=True)
    is_valid = models.BooleanField(verbose_name='是否有效', default=True)

    class Meta:
        db_table = 'record'
        verbose_name = verbose_name_plural = "客户拜访记录"
        ordering = ['-created_at']

    def __str__(self):
        return self.theme

customer/forms.py
from django.forms import ModelForm

from customer.models import Customer, CustomerShop, CustomerInvoice


class CustomerForm(ModelForm):
    """客户表单"""
    class Meta:
        model = Customer
        fields = ('name', 'rank', 'website', 'scale', 'nature', 'industry', 'remarks', 'user')


class CustomerShopForm(ModelForm):
    class Meta:
        model = CustomerShop
        exclude = ['created_at', 'updated_at']


class CustomerInvoiceForm(ModelForm):
    class Meta:
        model = CustomerInvoice
        exclude = ['created_at', 'updated_at']

customer/templates/customer.html
{% extends 'base.html' %}

{% block title %}
  <title>客户列表</title>
{% endblock %}

{% block container %}
  <blockquote class="layui-elem-quote">
    <a href="{% url 'customer' %}">客户</a>
    &ensp;/&ensp;
    <a href="javascript:;">客户列表</a>
  </blockquote>

  <hr class="layui-bg-green">

  <!--按钮组-->
  <form class="layui-form" action="." method="get">
    <div class="layui-form-customer" pane style="display: flex">
      <input type="search" name="name" placeholder="请输入客户名称进行搜索"
             autocomplete="off" class="layui-input">
    </div>
    <div class="layui-form-item" style="width: 50%; margin-top: 10px; display: flex;">
      <div class="layui-input-inline">
        <select name="rank">
          <option value="">请选择客户级别</option>
          <option value="1">重点客户</option>
          <option value="2">一般客户</option>
          <option value="3">普通客户</option>
        </select>
      </div>
      <div class="layui-input-inline">
        <select name="industry">
          <option value="">请选择客户行业</option>
          <option value="1">机台设备制造商</option>
          <option value="2">生产制造型企业</option>
          <option value="3">系统集成商</option>
          <option value="4">分销商</option>
          <option value="5">其它</option>
        </select>
      </div>
      <button class="layui-btn layui-btn-normal" lay-submit lay-filter="formDemo">提交搜索</button>
    </div>
  </form>

  <table class="layui-table">
    <colgroup>
      <col width="5%">
      <col>
      <col>
      <col>
      <col>
      <col>
      <col>
      <col width="10%">
    </colgroup>
    <thead>
    <tr>
      <th></th>
      <th>客户名称</th>
      <th>客户级别</th>
      <th>客户规模</th>
      <th>客户行业</th>
      <th>创建时间</th>
      <th>创建人</th>
      <th>操作</th>
    </tr>
    </thead>
    <tbody>
    <!--数据-->
    {% for customer in customers %}
      <tr>
        <td style="text-align: center">
          {{ forloop.counter }}
        </td>
        <td>
          <a style="color: #01AAED" href="{% url 'customer_detail' customer.id %}">{{ customer.name }}</a>
        </td>
        <td>
          {{ customer.get_rank_display }}
        </td>
        <td>
          {{ customer.get_scale_display }}
        </td>
        <td>
          {{ customer.get_industry_display|default_if_none:'' }}
        </td>
        <td>
          {{ customer.created_at }}
        </td>
        <td>
          {{ customer.user }}
        </td>
        <td>
          <div class="layui-btn-group">
            <a class="layui-btn layui-btn-sm layui-btn-normal" href="{% url 'customer_edit' customer.id %}">编辑</a>
            <a class="layui-btn layui-btn-sm layui-btn-danger"
               onclick="return deleteCus();" href="{% url 'customer_delete' customer.id %}">删除</a>
          </div>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

  <!--分页器-->
  {% if page_obj %}
    {% if page_obj.has_previous %}
      <a class="layui-btn layui-btn-normal layui-btn-sm" href="?page={{ page_obj.previous_page_number }}">上一页</a>
    {% endif %}
    <a class="layui-btn layui-btn-primary layui-btn-sm" href="javascript:;">当前页 {{ page_obj.number }}
      共 {{ paginator.num_pages }} 页.</a>
    {% if page_obj.has_next %}
      <a class="layui-btn layui-btn-normal layui-btn-sm" href="?page={{ page_obj.next_page_number }}">下一页</a>
    {% endif %}
  {% endif %}

{% endblock %}

{% block footer %}
  <script>
    //JavaScript代码区域
    layui.use(['element', 'laypage', 'form'], function(){
      var element = layui.element
      , laypage = layui.laypage
      , form = layui.form;
    });
  </script>
  <script type="text/javascript" language="JavaScript">
    function deleteCus() {
      if (confirm("确定要删除吗？")){
          return true;
      } else {
          return false;
      }
    }
  </script>
{% endblock %}

customer/templates/customer_all_detail.html
{% extends 'base.html' %}

{% block title %}
  <title>客户详情-{{ form.name.value }}</title>
{% endblock %}

{% block container %}
  <blockquote id="top" class="layui-elem-quote">
    <a href="{% url 'customer_all' %}">所有客户</a>
    &ensp;/&ensp;
    <a href="javascript:;">客户详情</a>
    &ensp;/&ensp;
    <a href="javascript:;">{{ form.name.value }}</a>
  </blockquote>

  <hr class="layui-bg-green">

  <!--客户详情-->
  <div id="1">
    <div class="layui-row layui-col-space10">
      <!--客户基本信息-->
      <div class="layui-col-md6">
        <form class="layui-form" action="" method="post">
          {% csrf_token %}
          <blockquote class="layui-elem-quote layui-quote-nm">客户基本信息</blockquote>
          <div class="layui-form-item">
            <label class="layui-form-label">客户名称</label>
            <div class="layui-input-block" style="pointer-events: none; cursor: not-allowed" style="pointer-events: none; cursor: not-allowed">
              <input type="text" name="name" required lay-verify="required"
                     autocomplete="off" class="layui-input"
                     value="{{ form.name.value|default_if_none:'' }}">
            </div>
          </div>
          <div class="layui-form-item">
            <label class="layui-form-label">客户级别</label>
            <div class="layui-input-block" style="pointer-events: none; cursor: not-allowed" style="pointer-events: none; cursor: not-allowed">
              {{ form.rank }}
            </div>
          </div>
          <div class="layui-form-item">
            <label class="layui-form-label">公司网址</label>
            <div class="layui-input-block" style="pointer-events: none; cursor: not-allowed">
              <input type="text" name="website"
                     autocomplete="off" class="layui-input"
                     value="{{ form.website.value|default_if_none:'' }}">
            </div>
          </div>
          <div class="layui-form-item">
            <label class="layui-form-label">客户规模</label>
            <div class="layui-input-block" style="pointer-events: none; cursor: not-allowed">
              {{ form.scale }}
            </div>
          </div>
          <div class="layui-form-item">
            <label class="layui-form-label">客户性质</label>
            <div class="layui-input-block" style="pointer-events: none; cursor: not-allowed">
              {{ form.nature }}
            </div>
          </div>
          <div class="layui-form-item">
            <label class="layui-form-label">客户行业</label>
            <div class="layui-input-block" style="pointer-events: none; cursor: not-allowed">
              {{ form.industry }}
            </div>
          </div>
          <div class="layui-form-item">
            <label class="layui-form-label">创建人</label>
            <div class="layui-input-block" style="pointer-events: none; cursor: not-allowed">
              {{ form.user }}
            </div>
          </div>
          {# 隐藏的表单，用户字段 #}
          <input type="hidden" name="user"
                 autocomplete="off" class="layui-input"
                 value="{{ request.session.user_id }}">
          {# 隐藏的表单，用户字段 #}
          <div class="layui-form-item layui-form-text">
            <label class="layui-form-label">备注信息</label>
            <div class="layui-input-block" style="pointer-events: none; cursor: not-allowed">
              <textarea name="remarks" class="layui-textarea" rows="7"
                        placeholder="请输入内容">{{ form.remarks.value|default_if_none:'' }}</textarea>
            </div>
          </div>
        </form>
      </div>
      <!--客户基本信息结束-->

      <!--客户地址信息-->
      <div class="layui-col-md6">
        <!--收货地址-->
        <form class="layui-form" action="" method="post">
          {% csrf_token %}
          <blockquote class="layui-elem-quote layui-quote-nm">收货地址和发票地址信息</blockquote>
          {# 隐藏的表单，客户名称外键字段 #}
          <input type="hidden" name="customer"
                 autocomplete="off" class="layui-input"
                 value="{{ pk }}">
          {# 隐藏的表单，客户名称外键字段 #}
          <div class="layui-form-item">
            <label class="layui-form-label">收货人</label>
            <div class="layui-input-block" style="pointer-events: none; cursor: not-allowed">
              <input type="text" name="shop_username"
                     autocomplete="off" class="layui-input"
                     value="{{ shopform.shop_username.value|default_if_none:'' }}">
            </div>
          </div>
          <div class="layui-form-item">
            <label class="layui-form-label">联系方式</label>
            <div class="layui-input-block" style="pointer-events: none; cursor: not-allowed">
              <input type="text" name="shop_phone" lay-verify="phone"
                     autocomplete="off" class="layui-input"
                     value="{{ shopform.shop_phone.value|default_if_none:'' }}">
            </div>
          </div>
          <div class="layui-form-item">
            <label class="layui-form-label">所在地区</label>
            <div class="layui-input-block" style="pointer-events: none; cursor: not-allowed">
              <div data-toggle="distpicker" style="display: flex">
                <div class="form-group">
                  <select class="form-control" lay-filter="shop_province"
                          data-province="{{ shopform.shop_province.value|default_if_none:'' }}"
                          name="shop_province" id="shop_province"></select>
                </div>
                <div class="form-group">
                  <select class="form-control" lay-filter="shop_city"
                          data-city="{{ shopform.shop_city.value|default_if_none:'' }}"
                          name="shop_city" id="shop_city"></select>
                </div>
                <div class="form-group">
                  <select class="form-control" lay-filter="shop_area"
                          data-district="{{ shopform.shop_area.value|default_if_none:'' }}"
                          name="shop_area" id="shop_area"></select>
                </div>
              </div>
            </div>
          </div>
          <div class="layui-form-item">
            <label class="layui-form-label">详细地址</label>
            <div class="layui-input-block" style="pointer-events: none; cursor: not-allowed">
              <input type="text" name="shop_address"
                     autocomplete="off" class="layui-input"
                     value="{{ shopform.shop_address.value|default_if_none:'' }}">
            </div>
          </div>
        </form>

        <!--发票地址-->
        <form class="layui-form" action="" method="post">
          {% csrf_token %}
{#          <blockquote class="layui-elem-quote layui-quote-nm">发票地址信息</blockquote>#}
          {# 隐藏的表单，客户名称外键字段 #}
          <input type="hidden" name="customer"
                 autocomplete="off" class="layui-input"
                 value="{{ pk }}">
          {# 隐藏的表单，客户名称外键字段 #}
          <div class="layui-form-item">
            <label class="layui-form-label">收货人</label>
            <div class="layui-input-block" style="pointer-events: none; cursor: not-allowed">
              <input type="text" name="invoice_username"
                     autocomplete="off" class="layui-input"
                     value="{{ invoiceform.invoice_username.value|default_if_none:'' }}">
            </div>
          </div>
          <div class="layui-form-item">
            <label class="layui-form-label">联系方式</label>
            <div class="layui-input-block" style="pointer-events: none; cursor: not-allowed">
              <input type="text" name="invoice_phone"
                     autocomplete="off" class="layui-input"
                     value="{{ invoiceform.invoice_phone.value|default_if_none:'' }}">
            </div>
          </div>
          <div class="layui-form-item">
            <label class="layui-form-label">所在地区</label>
            <div class="layui-input-block" style="pointer-events: none; cursor: not-allowed">
              <div data-toggle="distpicker" style="display: flex">
                <div class="form-group">
                  <select class="form-control" lay-filter="invoice_province"
                          data-province="{{ invoiceform.invoice_province.value|default_if_none:'' }}"
                          name="invoice_province" id="invoice_province"></select>
                </div>
                <div class="form-group">
                  <select class="form-control" lay-filter="invoice_city"
                          data-city="{{ invoiceform.invoice_city.value|default_if_none:'' }}"
                          name="invoice_city" id="invoice_city"></select>
                </div>
                <div class="form-group">
                  <select class="form-control" lay-filter="invoice_area"
                          data-district="{{ invoiceform.invoice_area.value|default_if_none:'' }}"
                          name="invoice_area" id="invoice_area"></select>
                </div>
              </div>
            </div>
          </div>
          <div class="layui-form-item">
            <label class="layui-form-label">详细地址</label>
            <div class="layui-input-block" style="pointer-events: none; cursor: not-allowed">
              <input type="text" name="invoice_address"
                     autocomplete="off" class="layui-input"
                     value="{{ invoiceform.invoice_address.value|default_if_none:'' }}">
            </div>
          </div>
        </form>
      </div>
      <!--客户地址信息结束-->
    </div>
  </div>
  <hr>
  <!--客户详情结束-->

  <!-- 联系人信息 -->
  <div id="3" class="layui-row">
    <blockquote class="layui-elem-quote layui-quote-nm">
      客户联系人信息
    </blockquote>
    <table class="layui-table">
      <colgroup>
        <col>
        <col>
        <col>
        <col>
        <col>
      </colgroup>
      <thead>
      <tr>
        <th>联系人姓名</th>
        <th>联系方式</th>
        <th>职位</th>
        <th>是否在职</th>
        <th>创建时间</th>
      </tr>
      </thead>
      <tbody>
      {% for liaison in liaisons %}
        <tr>
          <td>
            {{ liaison.name }}
          </td>
          <td>{{ liaison.phone }}</td>
          <td>{{ liaison.get_job_display }}</td>
          <td>{{ liaison.get_injob_display }}</td>
          <td>{{ liaison.created_at }}
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
  <hr>
  <!-- 联系人信息结束 -->

  <!-- 客户拜访记录 -->
  <div id="4" class="layui-row">
    <blockquote class="layui-elem-quote layui-quote-nm">
      客户拜访记录
    </blockquote>
    <table class="layui-table">
      <colgroup>
        <col>
        <col>
        <col>
        <col>
        <col>
      </colgroup>
      <thead>
      <tr>
        <th>拜访主题</th>
        <th>拜访方式</th>
        <th>主要事宜</th>
        <th>后续工作安排</th>
        <th>拜访时间</th>
      </tr>
      </thead>
      <tbody>
      {% for record in records %}
        <tr>
          <td>
            {{ record.theme }}
          </td>
          <td>{{ record.get_status_display }}</td>
          <td>{{ record.main }}</td>
          <td>{{ record.next }}</td>
          <td>{{ record.created_at|date:'Y年m月d日' }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
  <hr>
  <!-- 客户拜访记录结束 -->

  <!-- 客户商机 -->
  <div id="2" class="layui-row">
    <blockquote class="layui-elem-quote layui-quote-nm">
      客户商机
    </blockquote>

    <table class="layui-table">
      <colgroup>
        <col>
        <col>
        <col>
        <col>
        <col>
      </colgroup>
      <thead>
      <tr>
        <th>商机名称</th>
        <th>赢单率</th>
        <th>预估金额</th>
        <th>备注</th>
        <th>创建时间</th>
      </tr>
      </thead>
      <tbody>
      {% for business in businesses %}
        <tr>
          <td>
            {{ business.name }}
          </td>
          <td>{{ business.get_winning_rate_display }}</td>
          <td>{{ business.money }}</td>
          <td>{{ business.remarks|default_if_none:'无信息' }}</td>
          <td>{{ business.created_at }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
  <!-- 客户商机结束 -->
{% endblock %}

{% block footer %}
  <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
  <script src="/static/js/distpicker.js"></script>
  <script>
      //JavaScript代码区域
      layui.use(['element', 'form'], function () {
          var element = layui.element
              , form = layui.form;

          form.on('select(shop_province)', function (data) {
              $("#shop_province").val(data.value).change();
              form.render();
          })

          form.on('select(shop_city)', function (data) {
              $("#shop_city").val(data.value).change();
              form.render();
          })

          form.on('select(shop_area)', function (data) {
              $("#shop_area").val(data.value).change();
              form.render();
          })

          form.on('select(invoice_province)', function (data) {
              $("#invoice_province").val(data.value).change();
              form.render();
          })

          form.on('select(invoice_city)', function (data) {
              $("#invoice_city").val(data.value).change();
              form.render();
          })

          form.on('select(invoice_area)', function (data) {
              $("#invoice_area").val(data.value).change();
              form.render();
          })
      });
  </script>
{% endblock %}